### ISSUE TITLE
Mi 9 a13 bug 

### ISSUE THREAD

**Issue by axofhell** [PixelOS-Devices-old/device_xiaomi_cepheus#1]
Twitter won't open on my mi 9 phone, I can't log in to my Twitter account, there was no problem with the old version.

There are crashes in Google Chrome, it does not work stable, it causes the phone to reboot, sometimes the pages do not load.

**Comment by balgxmr** [comment]
> Twitter won't open on my mi 9 phone, I can't log in to my Twitter account, there was no problem with the old version.
> 
> There are crashes in Google Chrome, it does not work stable, it causes the phone to reboot, sometimes the pages do not load.

Hi, thanks for reporting. It's now fixed with latest release.
